export const cars = [
    {
        Name: 'DINKA JESTER',
        Price: 240000,
        Image: 'cars/jester/Jester-GTAV-front.webp',
        Image1: 'cars/jester/Jester-GTAV-RGSC-MainNew.webp',
        Image2: 'cars/jester/Jester-GTAV-RGSC-Action.webp',
        Image3: 'cars/jester/Jester-GTAO-RGSC-Action.webp',
        Description: 'Японский гибридно-электрический спортивный автомобиль с передней частью, напоминающей сердитую ухмылку, может показаться кому-то слишком причудливым, но с 4-литровым двигателем V6, мощностью 420 л.с. и максимальной скоростью 280 миль в час Dinka Jester по-прежнему обладает серьезной изюминкой.',
        TopSpeed: 4.1,
        Acceleration: 3.9,
        Braking: 2.3,
        Handling: 4
    },
    {
        Name: 'GROTTI ITALI GTO',
        Price: 1950000,
        Image: 'cars/italigto/ItaliGTO-GTAO-front.webp',
        Image1: 'cars/italigto/ItaliGTO-GTAO-RGSC-MainNew.webp',
        Image2: 'cars/italigto/GrottiItaliGTO-GTAO-Advertisement.webp',
        Image3: 'cars/italigto/11549-GTA5-2020-03-18-12-45-08-59.jpg',
        Description: 'Когда Вы думаете о лёгком редизайне, Вы, вероятно, думаете о кузове из углеродного волокна и урезанном интерьере. Но это только для новичков. Сядьте в Itali GTO, и воздух, которым вы задышите, будет содержать повышенное содержание водорода для дополнительной подъёмной силы. Grotti даже предприняли спорный шаг, обязав потенциальных владельцев внести свой вклад, сбрив волосы на теле и удалив по крайней мере одну почку. Иногда ради совершенства приходится страдать.',
        TopSpeed: 4.2,
        Acceleration: 5,
        Braking: 2.9,
        Handling: 4
    },
    {
        Name: 'RUNE CHEBUREK',
        Price: 145000,
        Image: 'cars/cheburek/Cheburek-GTAOnline-front.webp',
        Image1: 'cars/cheburek/Cheburek-GTAO-RGSC-MainNew.webp',
        Image2: 'cars/cheburek/8632-DYuKeD3XUAA5kw3.jpg',
        Image3: 'cars/cheburek/maxresdefault.jpg',
        Description: 'Пусть слой краски и лака Вас не смущает: Cheburek — ни что иное, как кусок железного занавеса, который пустили на переплавку в погоне за быстрой прибылью в условиях рыночной экономики. Что же касается слухов о том, что дизайн кузова отдали на откуп пятилетнему ребёнку с тяжёлым похмельным синдромом, мы можем заявить лишь одно: свободное предпринимательство — это прекрасно и мы всецело его поддерживаем.',
        TopSpeed: 3.8,
        Acceleration: 3.2,
        Braking: 1.2,
        Handling: 3.3
    },
    {
        Name: 'ANNIS ZR350',
        Price: 1615000,
        Image: 'cars/zr350/ZR350-GTAO-front.webp',
        Image1: 'cars/zr350/ZR350-GTAO-RGSC-Main.webp',
        Image2: 'cars/zr350/ZR350-GTAO-front.webp',
        Image3: 'cars/zr350/ZR350-GTAO-RearQuarter.webp',
        Description: 'Кивки узнавания, указания пальцем, фанаты, теряющие сознание в экстазе. Видеть, как мощный ZR350 набирает обороты, чтобы проделать дыру в подземной парковке, никогда не надоест. И когда вы сожжете эти шины, они будут бороться за то, кто сможет дышать вашими полициклическими ароматическими углеводородами, потому что такое большое влияние серьезно опьяняет.',
        TopSpeed: 4,
        Acceleration: 4.1,
        Braking: 1.3,
        Handling: 3.8
    },
    {
        Name: 'KARIN SULTAN RS',
        Price: 795000,
        Image: 'cars/sultanrs/SultanRS-GTAO-front.webp',
        Image1: 'cars/sultanrs/SultanRS-GTAO-BennysOriginalMotorWorks.webp',
        Image2: 'cars/sultanrs/KarinSultanRS-GTAO-SocialClub3.webp',
        Image3: 'cars/sultanrs/SultanRS-GTAO-October2021Advert.webp',
        Description: "Для младшего руководителя с широко раскрытыми глазами в конце 90-х ничто не говорило 'Я почти могу позволить себе купить европейца', как Karin Sultan. В наши дни Вы злой гонщик средних лет, страдающий диабетом, мечтающий стать раллийным гонщиком, но Sultan по-прежнему остается Вашим лучшим другом: с Вашими деньгами и нашим опытом он может стать высокооктановым гонщиком, о котором Вы мечтали в подростковом возрасте, и до сих пор понятия не имеете как водить. Подходит для модифицирования в Benny's Original Motor Works.",
        TopSpeed: 3.7,
        Acceleration: 4.1,
        Braking: 2.1,
        Handling: 3.9
    },
    {
        Name: 'ANNIS ELEGY RH8',
        Price: 95000,
        Image: 'cars/elegyrh8/ElegyRH8-GTAVe-front.webp',
        Image1: 'cars/elegyrh8/ElegyRH8-GTAV-RGSC-MainNew.webp',
        Image2: 'cars/elegyrh8/ElegyRH8-GTAV-RGSC-Action.webp',
        Image3: 'cars/elegyrh8/ElegyRH8-GTAO-RGSC-Action.webp',
        Description: 'Эта машина выкована в огне горы Фудзи и протестирована на немецких автобанах. И теперь Вы можете приобрести этого убийцу спорткаров не опасаясь визита агентов ФРБ — просто потому, что им больше нравится крушить импортные тачки, чем ловить террористов.',
        TopSpeed: 9,
        Acceleration: 9,
        Braking: 9,
        Handling: 9
    },
    {
        Name: 'ANNIS ELEGY RETRO CUSTOM',
        Price: 950000,
        Image: 'cars/elegyretro/ElegyRetroCustom-GTAO-front.webp',
        Image1: 'cars/elegyretro/ElegyRetroCustom-GTAO-RGSC-MainNew.webp',
        Image2: 'cars/elegyretro/ElegyRetroCustom-GTAO-RGSC-Action.webp',
        Image3: 'cars/elegyretro/ElegyRetroCustom-GTAO-RSC.webp',
        Description: 'В какой-то момент любой человек в Лос-Сантосе смотрел на гараж на десять машин, полный только стандартных Elegies, и задавался вопросом, какого черта они делают со своей жизнью. Что ж, благодаря Бенни вам больше нечего удивляться: теперь каждая из этих красавиц — это наполненная ностальгией, пропитанная модами ретро-классика начала 90-х, которая только и ждет своего часа.',
        TopSpeed: 4,
        Acceleration: 4.1,
        Braking: 1.8,
        Handling: 4.1
    },
    {
        Name: 'GROTTI TURISMO CLASSIC',
        Price: 705000,
        Image: 'cars/turismoclassic/TurismoClassic-GTAO-front.webp',
        Image1: 'cars/turismoclassic/TurismoClassic-GTAO-RGSC-MainNew.webp',
        Image2: 'cars/turismoclassic/TurismoClassic-GTAO-RGSC-Action.webp',
        Image3: 'cars/turismoclassic/TurismoClassic-GTAO-RSC.webp',
        Description: 'Это для пуристов. Никаких высокотехнологичных средств вождения. Никаких интеллектуальных функций безопасности. Когда вам осталось три наносекунды до того, чтобы набить рот идущему впереди грузовику, никакой бортовой суперкомпьютер вас не спасет (чё блять). Но точно так же, как изучение языка или убийство незнакомца голыми руками, этот вид тяжелой работы сам по себе является наградой.',
        TopSpeed: 4.1,
        Acceleration: 4.2,
        Braking: 0.8,
        Handling: 4
    },
    {
        Name: 'INVETERO COQUETTE D10',
        Price: 1510000,
        Image: 'cars/coquetted10/CoquetteD10-GTAO-front.webp',
        Image1: 'cars/coquetted10/CoquetteD10-GTAO-RGSC-MainNew.webp',
        Image2: 'cars/coquetted10/CoquetteD10-GTAO-RGSC-Action.webp',
        Image3: 'cars/coquetted10/CoquetteD10-GTAO-RearQuarter.webp',
        Description: 'Classic и Blackfin были зрелыми автомобилями, на которых вы любили ездить. Теперь смотрите, как они становятся зелеными и начинают вытекать тормозная жидкость при виде самой младшей модели Invetero. D10 — это классическая порода, одетая в пух и прах, загорелая спреем и обретшая вечную молодость. Эпоха пумы прошла. Настоящая Coquette наконец-то прибыла.',
        TopSpeed: 4.3,
        Acceleration: 4,
        Braking: 1,
        Handling: 5
    },
    {
        Name: 'TRUFFADE ADDER',
        Price: 1000000,
        Image: 'cars/adder/Adder-GTAV-front.webp',
        Image1: 'cars/adder/Adder-GTAV-RGSC-MainNew.webp',
        Image2: 'cars/adder/Adder-GTAO-RGSC-Action.webp',
        Image3: 'cars/adder/Adder-GTAV-RGSC-Action.webp',
        Description: 'Если провести аналогию между машинами и порно, эта красотка определённо была бы звездой самых откровенных и горячих сцен! Дайте, наконец, либералам реальный повод захлебнуться протестами: Adder — самый неэкологичный автомобиль на планете! Его чудовищный 8-литровый двигатель жрёт бензин быстрее, чем горящий нефтезавод, но зато позволяет разогнаться до 402 км/ч. Отличная машина для жизни в современном метрополисе.',
        TopSpeed: 4.3,
        Acceleration: 4,
        Braking: 1.8,
        Handling: 3.9
    },
    {
        Name: 'PEGASSI FAGGIO',
        Price: 5000,
        Image: 'cars/faggio/Faggio-GTAV-front.webp',
        Image1: 'cars/faggio/Faggio-GTAV-RGSC-MainNew.webp',
        Image2: 'cars/faggio/Faggio-GTAV-RGSC-Action.webp',
        Image3: 'cars/faggio/Faggio-GTAO-RGSC-Action.webp',
        Description: 'Скутеры нравятся только определённому типу мужчин. Вы что, один из них?',
        TopSpeed: 2.3,
        Acceleration: 1.1,
        Braking: 0.6,
        Handling: 2.2
    },
    {
        Name: 'PEGASSI FAGGIO MOD',
        Price: 55000,
        Image: 'cars/faggiomod/FaggioMod-GTAO-front.webp',
        Image1: 'cars/faggiomod/FaggioMod-GTAO-RGSC-MainNew.webp',
        Image2: 'cars/faggiomod/FaggioMod-GTAO-RGSC-Action.webp',
        Image3: 'cars/faggiomod/FaggioMod-GTAV-RSC.webp',
        Description: 'Определенный тип мужчин смотрит на скутер и думает: «Это нормально, но это не отражает того, насколько я уникален — для этого нужны интересные варианты модификаций». Если это вы (это так), то не волнуйтесь, ваш минутный поиск наконец-то подошел к концу.',
        TopSpeed: 2.3,
        Acceleration: 1.3,
        Braking: 0.6,
        Handling: 2.2
    },
    {
        Name: 'PEGASSI INFERNUS',
        Price: 440000,
        Image: 'cars/ifernus/Infernus-GTAV-front.webp',
        Image1: 'cars/ifernus/Infernus-GTAV-RGSC-Action.webp',
        Image2: 'cars/ifernus/Infernus-GTAO-RGSC-Action.webp',
        Image3: 'cars/ifernus/Infernus-GTAV-RSC.webp',
        Description: 'Итальянцы знают толк в пышных украшениях, сексуальных и безответственных тратах, как никто другой. Теперь и вы можете к ним присоединиться!',
        TopSpeed: 4,
        Acceleration: 4.2,
        Braking: 0.9,
        Handling: 4
    },
    {
        Name: 'PEGASSI INFERNUS CLASSIC',
        Price: 915000,
        Image: 'cars/infernusclassic/InfernusClassic-GTAO-front.webp',
        Image1: 'cars/infernusclassic/InfernusClassic-GTAO-RGSC-MainNew.webp',
        Image2: 'cars/infernusclassic/InfernusClassic-GTAO-RGSC-Action.webp',
        Image3: 'cars/infernusclassic/InfernusClassic-GTAV-RSC.webp',
        Description: 'Опыт подсказывает вам, что все настолько горячее должно быть безумием, и вы не ошибаетесь. Infernus Classic — это автомобиль, который поразит вас своими идеальными скулами, опустошит ваш банковский счет, а когда вы заснете на мокром участке, он прикончит вас ржавым мачете. Что не любить?',
        TopSpeed: 4,
        Acceleration: 4.1,
        Braking: 0.8,
        Handling: 4
    },
    {
        Name: 'KARIN CALICO GTF',
        Price: 1995000,
        Image: 'cars/calicogtf/CalicoGTF-GTAO-front.webp',
        Image1: 'cars/calicogtf/CalicoGTF-GTAO-RGSC-MainNew.webp',
        Image2: 'cars/calicogtf/CalicoGTF-GTAO-RGSC-Action.webp',
        Image3: 'cars/calicogtf/CalicoGTF-GTAOe-June2022Advert.webp',
        Description: 'О, девяностые. Из хаотического смешения гранжа, диалапа, феминизма третьей волны и полнометражной порнографии вышла Karin Calico GTF, машина, взявшая отовсюду понемногу и сделавшая из этого свой стиль: дух маслкара, раллийную смекалку, стритрейсерский имидж. Пора отложить липкую видеокассету и тряхнуть челкой: вас ждет домашняя работа.',
        TopSpeed: 4,
        Acceleration: 4.2,
        Braking: 1.2,
        Handling: 5
    },
]